
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'integration_tests'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'integration_tests'


model-paths: ["models"]
seed-paths: ["seeds"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models

seeds:  
  integration_tests:  
    +quote_columns: false


vars:
  loaddate: "1900-01-01"